version: "3.8"

services:
  nats:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}